#!/usr/bin/env bash
export EDITOR="nvim"
export TERM="screen-256color"
export BROWSER="firefox"
export STARSHIP_CONFIG="${HOME}/.config/starship/config.toml"
export GNUPGHOME="$HOME/.gnupg"
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM=auto
