textboxes:
  - title: ""
    position: [[24, 0], [27, 23]]
    rate-ms: 1000000
    color: 255
    sample: printf "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⠟⠛⠿⣿⣦⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡏⠀⠀⠀⠀⠉⠛⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠁⠀⠀⠀⠀⢠⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣼⣿⠀⠀⠀⢲⣶⣾⢹⣿⣣⣬⡝⢻⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣾⣿⣿⣿⣦⣄⠀⠀⠛⠿⣿⣿⣿⣿⣳⠌⠛⢦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⠏⠁⠀⠀⠉⠻⣷⡄⠀⠀⢠⣿⣿⣿⢻⠖⠊⠉⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⡇⠀⠀⠀⠀⠀⠀⠘⣿⠀⠀⣾⣿⣿⣧⡀⣀⣠⡼⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⡄⠀⠀⠀⠀⠀⢤⣄⣿⠀⠀⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⡿⣿⣧⡀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠉⠻⣿⣿⣿⠿⣿⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣴⡿⠋⠀⠹⣿⣿⣦⡀⠀⠀⠀⠀⠀⠹⣷⠀⠀⠀⠈⠀⠀⠀⠙⢷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣶⠿⠛⠁⠀⠀⠀⠀⣿⣿⠟⠛⢦⠀⠀⠀⠀⠀⣿⡆⠀⠀⠀⢀⠀⠀⡆⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⡶⠟⠛⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⢹⣇⠀⠀⠀⠁⠀⠀⠀⢠⣿⠀⠀⠀⠀⢸⠀⠀⣿⢸⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢻⣦⠀⠀⠀⠀⠀⠀⠈⢹⣷⣤⣀⣠⣾⣷⣾⣿⠀⠹⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⡿⠁⠀⠀⠀⠀⠀⠀⠀⢸⡄⠀⠀⠀⠀⠀⠀⠀⠀⢹⣷⡄⠀⠀⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⡇⠀⢠⠀⠀⠀⠀⠀⠀⣸⣷⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣰⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⣿⠀⠈⠙⢷⣄⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣷⣴⣿⠀⠀⠀⠀⠀⣰⣿⡟⠀⠀⠀⠀⢀⣀⣤⣾⣿⣿⣿⡏⠀⠀⠀⠀⠀⠀⣿⣏⢻⣿⣿⣿⣿⣷⣄⠀⠀⠹⡇⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⠇⠀⠀⠀⣠⣾⣿⣿⣿⣶⣶⣶⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⣸⣿⠀⣿⣿⣿⣿⣿⣿⣷⡄⠀⣿⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⠟⠀⠀⠐⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢿⣿⣿⣆⠀⠀⠀⠀⢹⣿⡟⠀⠹⣿⣿⣿⣿⣿⣿⣇⠀⣿⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⣠⣶⣿⡿⠋⠀⠀⣠⣾⣿⠏⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⠟⠀⠀⠀⠹⣿⣿⣷⣄⠀⠀⠈⣿⡇⠀⠀⠈⢿⣿⣿⣿⣿⣿⠀⢻⡆⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⣼⣿⣿⣯⣤⣤⣶⣿⡿⠟⠁⠀⠀⠀⣼⣿⣿⣿⣿⣿⠟⠋⠀⠀⠀⠀⠀⢹⣿⣿⡟⠀⠀⠀⠘⣇⠀⠀⠀⠀⣿⣿⣿⣿⣿⡄⠸⣇⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⢿⣿⣿⣿⣿⣿⣿⣷⡄⠀⠀⠀⠀⣼⣿⣿⣿⣿⣯⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣦⡀⠀⣀⣿⡆⠀⢠⣾⣿⣿⣿⣿⣿⣿⣶⣿⡇⠀⠀⠀⠀\n⣤⣤⣤⣤⣤⣼⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣶⣶⣾⣿⣿⣿⣿⣿⣷⣶⣶⣶⣶⣶⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣤⣤⣤⣤⣄\n⠀⠀⠀⠀⠀⠀⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠀⠀⠀⠀⠀⠀"
    border: false
  - title: "\U0001F553 Time"
    position: [[26, 23], [23, 10]]
    rate-ms: 1000
    color: 1
    sample: date "+%H:%M" | figlet -f roman
  - title: "\U0001F5D3️ Date"
    position: [[34, 33], [8, 4]]
    rate-ms: 60000
    color: 1
    sample: date "+%x"
