font_family Monaspace Neon
font_size 14
background_opacity 0.85
window_padding_width 0
hide_window_decorations yes
tab_bar_style hidden
confirm_os_window_close 0
cursor_shape block
cursor_blink_interval 0.5 ease-in-out
cursor_trail 5
cursor_trail_decay 0.1 0.25
cursor_trail_start_threshold 2
background #2D353B
foreground #D3C6AA
color0  #475258
color1  #E67E80
color2  #A7C080
color3  #DBBC7F
color4  #7FBBB3
color5  #D699B6
color6  #83C092
color7  #D3C6AA
color8  #475258
color9  #E67E80
color10 #A7C080
color11 #DBBC7F
color12 #7FBBB3
color13 #D699B6
color14 #83C092
color15 #D3C6AA
scrollback_lines 10000
enable_audio_bell no
