flameshot &
xrandr --output eDP-1 --primary --mode 1920x1080 --pos 3000x840 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 1080x840 --rotate normal --output DVI-I-2-1 --mode 1920x1080 --pos 0x0 --rotate right
exec i3
