flameshot &
xrandr --output eDP-1 --primary --mode 1920x1080 --pos 3840x0 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 1920x0 --rotate normal --output DVI-I-2-1 --mode 1920x1080 --pos 0x0 --rotate inverted
exec i3